export const GAME_IDS = [
  {
    title: 'A Plague Tale: Innocence - Windows 10',
    gamePassId: '9ND0CG3LM22K',
    metaCritic: 'a-plague-tale-innocence',
    howLongToBeat: '65080',
  },
  {
    title: 'Age of Empires Definitive Edition',
    gamePassId: '9NJWTJSVGVLJ',
    metaCritic: 'age-of-empires-definitive-edition',
    howLongToBeat: '49452',
  },
  {
    title: 'Age of Empires II: Definitive Edition',
    gamePassId: '9NJDD0JGPP2Q',
    metaCritic: 'age-of-empires-ii-definitive-edition',
    howLongToBeat: '68260',
  },
  {
    title: 'Age of Empires III: Definitive Edition',
    gamePassId: '9N1HF804QXN4',
    metaCritic: 'age-of-empires-iii-definitive-edition',
    howLongToBeat: '83883',
  },
  {
    title: 'Alan Wake',
    gamePassId: '9NKV44QF1R68',
    metaCritic: 'alan-wake',
    howLongToBeat: '319',
  },
  {
    title: 'Alien: Isolation',
    gamePassId: '9NSRJ872SGH7',
    metaCritic: 'alien-isolation',
    howLongToBeat: '16638',
  },
  {
    title: 'Alvastia Chronicles',
    gamePassId: '9MVJGBNNFPPS',
    metaCritic: 'alvastia-chronicles',
    howLongToBeat: '67659',
  },
  {
    title: 'Among Us',
    gamePassId: '9NG07QJNK38J',
    metaCritic: 'among-us',
    howLongToBeat: '74207',
  },
  {
    title: 'Ape Out',
    gamePassId: '9NR6DZ9F76P8',
    metaCritic: 'ape-out',
    howLongToBeat: '56938',
  },
  {
    title: "ARK: Survival Evolved Explorer's Edition",
    gamePassId: '9MT8ND8BS6NB',
    metaCritic: 'ark-survival-evolved',
    howLongToBeat: '26629',
  },
  {
    title: 'Astrologaster',
    gamePassId: '9NFT0CMC62DX',
    metaCritic: 'astrologaster',
    howLongToBeat: '67977',
  },
  {
    title: 'ASTRONEER',
    gamePassId: '9NBLGGH43KZB',
    metaCritic: 'astroneer',
    howLongToBeat: '42182',
  },
  {
    title: 'Battle Chasers: Nightwar',
    gamePassId: '9NT8XR7D5L00',
    metaCritic: 'battle-chasers-nightwar',
    howLongToBeat: '30017',
  },
  {
    title: 'Battlefleet Gothic: Armada 2 - Windows 10',
    gamePassId: '9NGWKW55M85P',
    metaCritic: 'battlefleet-gothic-armada-2',
    howLongToBeat: '64475',
  },
  {
    title: 'BATTLETECH',
    gamePassId: '9NQVDQS2BC10',
    metaCritic: 'battletech',
    howLongToBeat: '55977',
  },
  {
    title: 'Battletoads',
    gamePassId: '9N7GCF5SGCXC',
    metaCritic: 'battletoads',
    howLongToBeat: '80699',
  },
  {
    title: 'Blair Witch',
    gamePassId: '9NG7LG421V0Q',
    metaCritic: 'blair-witch',
    howLongToBeat: '68319',
  },
  {
    title: 'Bleeding Edge',
    gamePassId: '9NX6XGVJ0J3D',
    metaCritic: 'bleeding-edge',
    howLongToBeat: '68093',
  },
  {
    title: 'Bloodstained: Ritual of the Night',
    gamePassId: '9MWB2BFF0SPD',
    metaCritic: 'bloodstained-ritual-of-the-night',
    howLongToBeat: '26266',
  },
  {
    title: 'Bridge Constructor Portal',
    gamePassId: '9PDXF172R7VJ',
    metaCritic: 'bloodstained-ritual-of-the-night',
    howLongToBeat: '26266',
  },
  {
    title: 'Broforce',
    gamePassId: '9P03ZQMBMV65',
    metaCritic: 'broforce',
    howLongToBeat: '17638',
  },
  {
    title: 'Call of the Sea',
    gamePassId: '9NNG78K7N91K',
    metaCritic: 'call-of-the-sea',
    howLongToBeat: '77918',
  },
  {
    title: 'Carrion',
    gamePassId: '9MSMJH3C6TKR',
    metaCritic: 'carrion',
    howLongToBeat: '68169',
  },
  {
    title: 'Carto',
    gamePassId: '9PFS8Q01C2C4',
    metaCritic: '',
    howLongToBeat: '80570',
  },
  {
    title: 'Celeste',
    gamePassId: 'BWMQL2RPWBHB',
    metaCritic: 'celeste',
    howLongToBeat: '42818',
  },
  {
    title: 'Children of Morta',
    gamePassId: '9P675WH90SB4',
    metaCritic: 'children-of-morta',
    howLongToBeat: '22534',
  },
  {
    title: 'Cities: Skylines - Windows 10 Edition',
    gamePassId: '9NWVC7XP3PFD',
    metaCritic: 'cities-skylines',
    howLongToBeat: '24640',
  },
  {
    title: 'Clustertruck',
    gamePassId: '9N8WVMD7J5GQ',
    metaCritic: 'clustertruck',
    howLongToBeat: '40215',
  },
  {
    title: 'Comanche (Game Preview)',
    gamePassId: '9N2H2GRB4D0K',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Company of Heroes 2: Complete Collection',
    gamePassId: '9NX9WH5F0RZD',
    metaCritic: 'company-of-heroes-2',
    howLongToBeat: '1875',
  },
  {
    title: 'Control Standard Edition',
    gamePassId: '9PL1J8PJKH29',
    metaCritic: 'control',
    howLongToBeat: '57507',
  },
  {
    title: 'Crackdown 3',
    gamePassId: '9NXR6469DM2P',
    metaCritic: 'crackdown-3',
    howLongToBeat: '38828',
  },
  {
    title: 'CrossCode',
    gamePassId: '9NFDPQ0KZ6RN',
    metaCritic: 'crosscode',
    howLongToBeat: '24970',
  },
  {
    title: 'Crossing Souls',
    gamePassId: '9PD1Z95CNTW4',
    metaCritic: 'crossing-souls',
    howLongToBeat: '25103',
  },
  {
    title: 'Crusader Kings III',
    gamePassId: '9N7GG222GTTH',
    metaCritic: 'crusader-kings-iii',
    howLongToBeat: '71763',
  },
  {
    title: 'Cyber Shadow',
    gamePassId: '9NX9LJ5JSWH8',
    metaCritic: 'cyber-shadow',
    howLongToBeat: '42816',
  },
  {
    title: 'Darksiders Genesis',
    gamePassId: '9NJ5X04M30HN',
    metaCritic: 'darksiders-genesis',
    howLongToBeat: '68043',
  },
  {
    title: 'Day of the Tentacle Remastered',
    gamePassId: '9NKK6CX54183',
    metaCritic: 'day-of-the-tentacle-remastered',
    howLongToBeat: '35880',
  },
  {
    title: 'Dead by Daylight Windows',
    gamePassId: '9NMS4SFNBGBH',
    metaCritic: 'dead-by-daylight',
    howLongToBeat: '37986',
  },
  {
    title: 'Dead Cells',
    gamePassId: '9NKVX66J0ZSK',
    metaCritic: 'dead-cells',
    howLongToBeat: '45727',
  },
  {
    title: 'Deep Rock Galactic',
    gamePassId: '9NHFVWX1V7QJ',
    metaCritic: 'deep-rock-galactic',
    howLongToBeat: '47169',
  },
  {
    title: 'Deliver Us The Moon',
    gamePassId: '9PF6BS5DGNLX',
    metaCritic: 'deliver-us-the-moon',
    howLongToBeat: '71372',
  },
  {
    title: 'Descenders',
    gamePassId: 'C37XBX7DCBZ0',
    metaCritic: 'descenders',
    howLongToBeat: '71372',
  },
  {
    title: 'Desperados III',
    gamePassId: '9P1ZX74WPL68',
    metaCritic: 'desperados-iii',
    howLongToBeat: '60291',
  },
  {
    title: 'Disgaea 4 Complete+',
    gamePassId: '9PFJDSL1CC7G',
    metaCritic: 'disgaea-4-complete+',
    howLongToBeat: '71701',
  },
  {
    title: 'Dishonored 2',
    gamePassId: '9MW4RJDRSF78',
    metaCritic: 'dishonored-2',
    howLongToBeat: '26731',
  },
  {
    title: 'Disneyland Adventures',
    gamePassId: '9N6Z8DQXSQWH',
    metaCritic: 'disneyland-adventures',
    howLongToBeat: '4994',
  },
  {
    title: "Don't Starve: Giant Edition",
    gamePassId: 'C0XBNVR137DZ',
    metaCritic: 'dont-starve',
    howLongToBeat: '2675',
  },
  {
    title: 'Donut County',
    gamePassId: '9N6V2181GHLM',
    metaCritic: 'donut-county',
    howLongToBeat: '51323',
  },
  {
    title: 'DOOM Eternal Standard Edition (PC)',
    gamePassId: '9PK09BL31FK1',
    metaCritic: 'doom-eternal',
    howLongToBeat: '57506',
  },
  {
    title: 'Double Kick Heroes',
    gamePassId: '9NJPT63K27W8',
    metaCritic: 'double-kick-heroes',
    howLongToBeat: '53061',
  },
  {
    title: 'Downwell',
    gamePassId: '9P641Z19NT2S',
    metaCritic: 'downwell',
    howLongToBeat: '31178',
  },
  {
    title: 'DRAGON QUEST® XI S: Echoes of an Elusive Age™ - Definitive Edition',
    gamePassId: '9PBDC0XZ8TXK',
    metaCritic: 'dragon-quest-xi-echoes-of-an-elusive-age',
    howLongToBeat: '69743',
  },
  {
    title: 'Drake Hollow',
    gamePassId: '9PGNGGWBX1NR',
    metaCritic: 'drake-hollow',
    howLongToBeat: '82637',
  },
  {
    title: 'Dungeon of the Endless™',
    gamePassId: '9N46K0X6TBZK',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Eastshade',
    gamePassId: '9PLCR0FR564K',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Endless Legend',
    gamePassId: '9NP09BFQNHCJ',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Endless Space 2: Deluxe Edition',
    gamePassId: '9NV3Q7WVN2RB',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Enter The Gungeon',
    gamePassId: '9NB65S6LFZRT',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Europa Universalis IV - Microsoft Store Edition',
    gamePassId: '9PHQJWGLTZM8',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'F1® 2019 PC',
    gamePassId: '9NL9VGSH00LL',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Fallout 76 - PC',
    gamePassId: '9NKGNMNK3K3Z',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'FINAL FANTASY IX',
    gamePassId: '9NPGTNQFC8B5',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'FINAL FANTASY VII WINDOWS EDITION',
    gamePassId: '9PN0W216SKZB',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'FINAL FANTASY VIII Remastered WINDOWS EDITION',
    gamePassId: '9P35DPLN1JCN',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: "Five Nights at Freddy's",
    gamePassId: '9N5253J559LR',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: "Five Nights at Freddy's 2",
    gamePassId: '9NBR2ZSD99FX',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: "Five Nights at Freddy's 3",
    gamePassId: '9P6N7LQ4HZFD',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: "Five Nights at Freddy's 4",
    gamePassId: '9PLDLMPLR7JV',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: "Five Nights at Freddy's: Original Series",
    gamePassId: '9PJ2DSSXZR0P',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'For The King',
    gamePassId: '9NS1CD1V4BKW',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Forager',
    gamePassId: '9P5SFDNW6V13',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Forza Horizon 4 Standard Edition',
    gamePassId: '9PNJXVCVWD4K',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Forza Motorsport 7 Standard Edition',
    gamePassId: '9N3NK5WW05HT',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Frostpunk',
    gamePassId: '9NS0KH25D76X',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Full Throttle Remastered',
    gamePassId: '9P3ZRGNQVC7D',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Gato Roboto',
    gamePassId: '9PBJQ90CT236',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Gears 5',
    gamePassId: 'C2KDNLT2H7DM',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Gears 5 Game of the Year Edition',
    gamePassId: '9P4KMR76PLLQ',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Gears of War 4',
    gamePassId: '9NBLGGH4PBBM',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Gears of War: Ultimate Edition for Windows 10',
    gamePassId: '9NBLGGH3SHM5',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Gears Tactics',
    gamePassId: '9NN3HCKW5TPC',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Ghost of a Tale',
    gamePassId: '9PJR5XZG5CNS',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Goat Simulator Windows 10',
    gamePassId: '9MXWKHJ3VZZH',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Golf With Your Friends',
    gamePassId: '9MVK5W0HMRP7',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'GONNER2 WIN10',
    gamePassId: '9P44W70MC99Z',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'GreedFall - Windows 10',
    gamePassId: '9PB79JST8PDH',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Grim Fandango Remastered',
    gamePassId: '9PC288TN7R8K',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Grounded - Game Preview',
    gamePassId: '9PJTHRNVH62H',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Guacamelee! 2',
    gamePassId: '9NVK1W7L093S',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Halo 2: Anniversary',
    gamePassId: '9P5739G419LD',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Halo 3',
    gamePassId: '9PGL2Z1H9M4R',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Halo 3: ODST',
    gamePassId: '9P6VZCRGXFMX',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Halo 4',
    gamePassId: '9P8CFXZH93CK',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Halo Wars 2',
    gamePassId: '9NBLGGH5WMKM',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Halo Wars 2: Standard Edition',
    gamePassId: '9NBLGGH515BD',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Halo Wars: Definitive Edition (PC)',
    gamePassId: '9NBLGGH5WLR0',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Halo: Combat Evolved Anniversary',
    gamePassId: '9NWQMVSB63N4',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Halo: Reach',
    gamePassId: '9N9WZT3PJ27W',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Halo: Spartan Assault',
    gamePassId: '9WZDNCRFHWFH',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Halo: Spartan Strike',
    gamePassId: '9WZDNCRFJBFJ',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Halo: The Master Chief Collection',
    gamePassId: '9NTM9HXNLSZX',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Haven',
    gamePassId: '9NZL91Q08XRV',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Hearts of Iron IV: Cadet Edition',
    gamePassId: '9NF6WPNS1S73',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Heave Ho',
    gamePassId: '9P8JHRDVBLHB',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: "Hellblade: Senua's Sacrifice",
    gamePassId: '9NCLP4LV5K7Z',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Hello Neighbor',
    gamePassId: '9NDDH3R9DF40',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Hollow Knight',
    gamePassId: '9PKM22F7C9K5',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Hotline Miami',
    gamePassId: '9PPCS86WS28Z',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Human Fall Flat',
    gamePassId: '9MT4HS1CP72W',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'HyperDot',
    gamePassId: '9NVVJ8TBD7KP',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Hypnospace Outlaw',
    gamePassId: '9PM3NVB3PXG0',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Ikenfell',
    gamePassId: '9N2X1J99S4M9',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Injustice™ 2 - Standard Edition',
    gamePassId: '9PHT4W7WBBDQ',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'It Lurks Below',
    gamePassId: '9PFW68JLS81F',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Katana Zero',
    gamePassId: '9P6CVNVMK56R',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Kathy Rain',
    gamePassId: '9P8HN2T2SZGB',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Killer Instinct: Definitive Edition',
    gamePassId: '9NBLGGH51BMC',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Knights and Bikes',
    gamePassId: '9P64KV1HQK07',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Levelhead',
    gamePassId: '9PJZBB8FWK8H',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Lonely Mountains: Downhill',
    gamePassId: '9MV6MCVLT8GR',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Machinarium',
    gamePassId: '9N83GKZLC8BK',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'MARVEL VS. CAPCOM: INFINITE',
    gamePassId: '9PGSCB1X2P7G',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'MechWarrior 5: Mercenaries',
    gamePassId: '9PB86W3JK8Z5',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Microsoft Flight Simulator: Standard',
    gamePassId: '9NXN8GF8N9HT',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Middle-earth™: Shadow of War™',
    gamePassId: '9PDV8FKWP3B4',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Minecraft Dungeons - Windows 10',
    gamePassId: '9P8MK4NC0LJB',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'MISTOVER',
    gamePassId: '9P8K66J3CQ9S',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Momodora: Reverie Under the Moonlight',
    gamePassId: '9NZL00LF4V58',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Monster Sanctuary',
    gamePassId: '9PBWWQGXVMKC',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Monster Train',
    gamePassId: '9NP4BGBLLLXM',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Moonlighter',
    gamePassId: '9P8XJRLCLH2P',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Morkredd',
    gamePassId: '9PKD7RG0TQP4',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Mother Russia Bleeds',
    gamePassId: '9NVFHBKDLPM4',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'MotoGP™20 - Windows Edition',
    gamePassId: '9N88HSBP6RJ8',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Mount & Blade: Warband PC',
    gamePassId: '9PFZC53PVTDB',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Moving Out',
    gamePassId: '9N9H593X8SVP',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'My Time At Portia',
    gamePassId: '9NBLSN1JP7TH',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Neon Abyss',
    gamePassId: '9PLWSGHFQ4PS',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Neoverse',
    gamePassId: '9NNSTP6KJTZ9',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: "New Super Lucky's Tale",
    gamePassId: '9MZN3SMXN824',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Night Call',
    gamePassId: '9N5KSQG0R9TB',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Night in the Woods Win10',
    gamePassId: '9MV13BTTCKLL',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: "No Man's Sky",
    gamePassId: 'BQVQTL3PCH05',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Nowhere Prophet',
    gamePassId: '9P01NRSZCVR6',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Observation',
    gamePassId: '9PBLH1322GX0',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Ori and the Blind Forest: Definitive Edition',
    gamePassId: '9NBLGGH1Z6FB',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Ori and the Will of the Wisps',
    gamePassId: '9N8CD0XZKLP4',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Out of the Park Baseball 21',
    gamePassId: '9NNW9V8DVPG6',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Overcooked! 2',
    gamePassId: '9PGB72NFG5JN',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Oxenfree',
    gamePassId: '9NBLGGH6CTZ5',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Pandemic: The Board Game',
    gamePassId: '9P8Q4W21QQZ2',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Phoenix Point',
    gamePassId: '9P1P5Q3BNM7J',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Pikuniku Win10',
    gamePassId: '9N8QNKN5ZKTH',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Pillars of Eternity: Hero Edition',
    gamePassId: '9P5LZC1KB48V',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Plebby Quest: The Crusades',
    gamePassId: '9MWBPSQ5PKQR',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Power Rangers: Battle for the Grid',
    gamePassId: '9P5VMG8D4P4B',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Prison Architect PC',
    gamePassId: '9P5S2J2VLLPR',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Project Winter',
    gamePassId: '9P3SX4G50LZ1',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'RAGE 2 (PC)',
    gamePassId: '9P2J7WHV0K4N',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'ReCore',
    gamePassId: '9NBLGGH1Z6FQ',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'RESIDENT EVIL 7 biohazard',
    gamePassId: '9NBLGGH4SPK6',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Rise of Nations: Extended Edition',
    gamePassId: '9NS84HCWZD8B',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'River City Girls',
    gamePassId: '9PGNT102001S',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Rush: A DisneyPixar Adventure',
    gamePassId: '9P3PL76N0KWZ',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'ScourgeBringer',
    gamePassId: '9NXPV1T3WS34',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Sea of Thieves',
    gamePassId: '9P2N57MC619K',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Shadow Warrior 2',
    gamePassId: '9P6SFBR1TCWQ',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Slay The Spire',
    gamePassId: '9MZQR8317S3B',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Spiritfarer®',
    gamePassId: '9NG5L58FD3X5',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Star Renegades',
    gamePassId: '9PK5S1QKV10D',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Starbound',
    gamePassId: '9MTSBWPWPQVQ',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'State of Decay 2: Juggernaut Edition',
    gamePassId: '9NT4X7P8B9NB',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Stellaris',
    gamePassId: '9NXQPGMR917R',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Stranger Things 3: The Game',
    gamePassId: '9PMDDQ228FQD',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Streets of Rage 4',
    gamePassId: '9N7H54KNCB9N',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Streets of Rogue',
    gamePassId: '9NKRBSZXQ2HM',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Subnautica',
    gamePassId: 'BX3S1Q5DVHRD',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Sunset Overdrive',
    gamePassId: '9NNLBL0T2Z43',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: "Super Lucky's Tale",
    gamePassId: '9PLMGFWCFZ9G',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Surviving Mars',
    gamePassId: '9MXB71Q4VWGJ',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Tales of Vesperia™: Definitive Edition',
    gamePassId: '9N5QWL08HRTR',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Tell Me Why: Chapters 1-3',
    gamePassId: '9NF83PRZK6K3',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Tetris® Effect: Connected',
    gamePassId: '9PPBVK3TK83M',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: "The Bard's Tale ARPG : Remastered and Resnarkled",
    gamePassId: '9PN3VDFTB5HZ',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: "The Bard's Tale IV: Director's Cut",
    gamePassId: 'C2B4T86TXLRS',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: "The Bard's Tale Trilogy",
    gamePassId: '9MVN4ND41DD3',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'The Dark Crystal: Age of Resistance Tactics',
    gamePassId: '9NPWSCWJGHL1',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'The Dark Pictures Anthology: Man Of Medan',
    gamePassId: '9N3TF0CG8NZB',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'The Falconeer',
    gamePassId: '9N8J0T5HCDB9',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'The Gardens Between',
    gamePassId: '9P4Z4TW66LPV',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'The Long Dark',
    gamePassId: '9NFKN56ZBMR0',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'The Medium',
    gamePassId: '9NFSR96G6K4N',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'The Messenger',
    gamePassId: '9NNFBW3NGV9K',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'The Outer Worlds',
    gamePassId: '9MWD2Z8L1FBQ',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'The Surge 2 - Windows 10',
    gamePassId: '9NLDM4DGX41G',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: "The Swords of Ditto: Mormo's Curse",
    gamePassId: '9NF2DDV5RTH8',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'The Touryst',
    gamePassId: '9N9W1JK1X5QJ',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'The Yakuza Remastered Collection for Windows 10',
    gamePassId: '9NBTL551XL5N',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Thumper',
    gamePassId: '9PHV10KXLJZT',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Torment: Tides of Numenera',
    gamePassId: '9NC0071DJ6XC',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Totally Accurate Battle Simulator (Game Preview)',
    gamePassId: '9PC4RWP34M2D',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Touhou Luna Nights',
    gamePassId: '9NBLGJQQBHH4',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Trailmakers',
    gamePassId: '9NSFGM8J6MBJ',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Train Sim World® 2020',
    gamePassId: '9PMT49X8ZGM2',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Two Point Hospital™',
    gamePassId: '9N08S5VPC4SX',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'UnderMine',
    gamePassId: '9N52CQMFH3BB',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Unruly Heroes Windows 10',
    gamePassId: '9P3SS6K8ZQ57',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Unto The End',
    gamePassId: '9MVJ0W5N2L2Q',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'VA-11 Hall-A: Cyberpunk Bartender Action',
    gamePassId: '9P9C1HB78K05',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Vambrace: Cold Soul',
    gamePassId: '9N171CGFVT1L',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Void Bastards',
    gamePassId: '9PJ1CGLKQSWS',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Wargroove',
    gamePassId: '9NRPTTJ94PCK',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: "Wasteland 2: Director's Cut",
    gamePassId: 'C521HDXRTS7F',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Wasteland 3 (PC)',
    gamePassId: '9NLT5XR52ZS7',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Wasteland Remastered',
    gamePassId: '9NGH1FK0RJGL',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'We Happy Few',
    gamePassId: '9NBLGGH5342P',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'West of Dead',
    gamePassId: '9NV0540N4JRN',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'What Remains of Edith Finch',
    gamePassId: 'BSLGLG8P9T01',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: "Wilmot's Warehouse Win10",
    gamePassId: '9NCHVR5KH0RN',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Wizard of Legend',
    gamePassId: '9MZH0GG41HL9',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Wolfenstein: Youngblood (PC)',
    gamePassId: '9PHFTS44F99K',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'WORLD OF HORROR (Game Preview)',
    gamePassId: '9N1FDTTSS49Z',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'World War Z',
    gamePassId: '9N015DFDMVK6',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Worms W.M.D',
    gamePassId: '9NVRZZJ4NG99',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Xeno Crisis',
    gamePassId: '9PNBGZTL0Z1S',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Yakuza 0 for Windows 10',
    gamePassId: '9PD0BJRBLRJM',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Yakuza 3 Remastered for Windows 10',
    gamePassId: '9NC4QMRHCNZK',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Yakuza 4 Remastered for Windows 10',
    gamePassId: '9NWZTB9JQG9S',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Yakuza 5 Remastered for Windows 10',
    gamePassId: '9MVX1V7W5SW8',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Yakuza Kiwami 2 for Windows 10',
    gamePassId: '9MZNFNN3XJ3F',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Yakuza Kiwami for Windows 10',
    gamePassId: '9P40SC5DQ9K0',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Yes, Your Grace',
    gamePassId: '9NX14Q0QZD1T',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'YIIK: A Postmodern RPG',
    gamePassId: '9P3XR9QN0P4C',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Yooka-Laylee and the Impossible Lair',
    gamePassId: '9NB1LCQDPPM1',
    metaCritic: '',
    howLongToBeat: '',
  },
  {
    title: 'Zoo Tycoon: Ultimate Animal Collection',
    gamePassId: '9PJ06TZX4NMH',
    metaCritic: '',
    howLongToBeat: '',
  },
]
