exports.GAME_IDS = [
  {
    howLongToBeatId: '65080',
    metaCriticId: 'a-plague-tale-innocence',
    title: 'A Plague Tale: Innocence',
    gamePassId: '9ND0CG3LM22K',
  },
  {
    howLongToBeatId: '68260',
    metaCriticId: 'age-of-empires-definitive-edition',
    title: 'Age of Empires Definitive Edition',
    gamePassId: '9NJWTJSVGVLJ',
  },
  {
    howLongToBeatId: '68260',
    metaCriticId: 'age-of-empires-ii-definitive-edition',
    title: 'Age of Empires II: Definitive Edition',
    gamePassId: '9NJDD0JGPP2Q',
  },
  {
    howLongToBeatId: '83883',
    metaCriticId: 'age-of-empires-iii-definitive-edition',
    title: 'Age of Empires III: Definitive Edition',
    gamePassId: '9N1HF804QXN4',
  },
  {
    howLongToBeatId: '319',
    metaCriticId: 'alan-wake',
    title: 'Alan Wake',
    gamePassId: '9NKV44QF1R68',
  },
  {
    howLongToBeatId: '16638',
    metaCriticId: 'alien-isolation',
    title: 'Alien: Isolation',
    gamePassId: '9NSRJ872SGH7',
  },
  {
    howLongToBeatId: '67659',
    metaCriticId: 'alvastia-chronicles',
    title: 'Alvastia Chronicles',
    gamePassId: '9MVJGBNNFPPS',
  },
  {
    howLongToBeatId: '74207',
    metaCriticId: 'the-wolf-among-us',
    title: 'Among Us',
    gamePassId: '9NG07QJNK38J',
  },
  {
    howLongToBeatId: '56938',
    metaCriticId: 'ape-out',
    title: 'Ape Out',
    gamePassId: '9NR6DZ9F76P8',
  },
  {
    howLongToBeatId: '26629',
    metaCriticId: 'ark-survival-evolved',
    title: 'ARK: Survival Evolved',
    gamePassId: '9MT8ND8BS6NB',
  },
  {
    howLongToBeatId: '67977',
    metaCriticId: 'astrologaster',
    title: 'Astrologaster',
    gamePassId: '9NFT0CMC62DX',
  },
  {
    howLongToBeatId: '42182',
    metaCriticId: 'astroneer',
    title: 'ASTRONEER',
    gamePassId: '9NBLGGH43KZB',
  },
  {
    howLongToBeatId: '30017',
    metaCriticId: 'battle-chasers-nightwar',
    title: 'Battle Chasers: Nightwar',
    gamePassId: '9NT8XR7D5L00',
  },
  {
    howLongToBeatId: '64475',
    metaCriticId: 'battlefleet-gothic-armada-2',
    title: 'Battlefleet Gothic: Armada 2',
    gamePassId: '9NGWKW55M85P',
  },
  {
    howLongToBeatId: '55977',
    metaCriticId: 'battletech',
    title: 'BATTLETECH',
    gamePassId: '9NQVDQS2BC10',
  },
  {
    howLongToBeatId: '80699',
    metaCriticId: 'battletoads',
    title: 'Battletoads',
    gamePassId: '9N7GCF5SGCXC',
  },
  {
    howLongToBeatId: '68319',
    metaCriticId: 'blair-witch',
    title: 'Blair Witch',
    gamePassId: '9NG7LG421V0Q',
  },
  {
    howLongToBeatId: '68093',
    metaCriticId: 'bleeding-edge',
    title: 'Bleeding Edge',
    gamePassId: '9NX6XGVJ0J3D',
  },
  {
    howLongToBeatId: '26266',
    metaCriticId: 'bloodstained-ritual-of-the-night',
    title: 'Bloodstained: Ritual of the Night',
    gamePassId: '9MWB2BFF0SPD',
  },
  {
    howLongToBeatId: '51365',
    metaCriticId: 'bridge-constructor-portal',
    title: 'Bridge Constructor Portal',
    gamePassId: '9PDXF172R7VJ',
  },
  {
    howLongToBeatId: '17638',
    metaCriticId: 'broforce',
    title: 'Broforce',
    gamePassId: '9P03ZQMBMV65',
  },
  {
    howLongToBeatId: '77918',
    metaCriticId: 'call-of-the-sea',
    title: 'Call of the Sea',
    gamePassId: '9NNG78K7N91K',
  },
  {
    howLongToBeatId: '68169',
    metaCriticId: 'carrion',
    title: 'Carrion',
    gamePassId: '9MSMJH3C6TKR',
  },
  {
    howLongToBeatId: '80570',
    metaCriticId: 'cartoon-network-universe-fusionfall',
    title: 'Carto',
    gamePassId: '9PFS8Q01C2C4',
  },
  {
    howLongToBeatId: '42818',
    metaCriticId: 'celeste',
    title: 'Celeste',
    gamePassId: 'BWMQL2RPWBHB',
  },
  {
    howLongToBeatId: '22534',
    metaCriticId: 'children-of-morta',
    title: 'Children of Morta',
    gamePassId: '9P675WH90SB4',
  },
  {
    howLongToBeatId: '24640',
    metaCriticId: 'cities-skylines',
    title: 'Cities: Skylines',
    gamePassId: '9NWVC7XP3PFD',
  },
  {
    howLongToBeatId: '40215',
    metaCriticId: 'clustertruck',
    title: 'Clustertruck',
    gamePassId: '9N8WVMD7J5GQ',
  },
  {
    howLongToBeatId: '72601',
    metaCriticId: 'enemy-engaged-rah-66-comanche-versus-ka-52-hokum',
    title: 'Comanche ',
    gamePassId: '9N2H2GRB4D0K',
  },
  {
    howLongToBeatId: '1875',
    metaCriticId: 'company-of-heroes-2',
    title: 'Company of Heroes 2',
    gamePassId: '9NX9WH5F0RZD',
  },
  {
    howLongToBeatId: '57507',
    metaCriticId: 'superhot-mind-control-delete',
    title: 'Control ',
    gamePassId: '9PL1J8PJKH29',
  },
  {
    howLongToBeatId: '38828',
    metaCriticId: 'crackdown-3',
    title: 'Crackdown 3',
    gamePassId: '9NXR6469DM2P',
  },
  {
    howLongToBeatId: '24970',
    metaCriticId: 'crosscode',
    title: 'CrossCode',
    gamePassId: '9NFDPQ0KZ6RN',
  },
  {
    howLongToBeatId: '25103',
    metaCriticId: 'crossing-souls',
    title: 'Crossing Souls',
    gamePassId: '9PD1Z95CNTW4',
  },
  {
    howLongToBeatId: '71763',
    metaCriticId: 'crusader-kings-iii',
    title: 'Crusader Kings III',
    gamePassId: '9N7GG222GTTH',
  },
  {
    howLongToBeatId: '42816',
    metaCriticId: 'cyber-shadow',
    title: 'Cyber Shadow',
    gamePassId: '9NX9LJ5JSWH8',
  },
  {
    howLongToBeatId: '68043',
    metaCriticId: 'darksiders-genesis',
    title: 'Darksiders Genesis',
    gamePassId: '9NJ5X04M30HN',
  },
  {
    howLongToBeatId: '35880',
    metaCriticId: 'day-of-the-tentacle-remastered',
    title: 'Day of the Tentacle Remastered',
    gamePassId: '9NKK6CX54183',
  },
  {
    howLongToBeatId: '37986',
    metaCriticId: 'dead-by-daylight',
    title: 'Dead by Daylight ',
    gamePassId: '9NMS4SFNBGBH',
  },
  {
    howLongToBeatId: '45727',
    metaCriticId: 'dead-cells',
    title: 'Dead Cells',
    gamePassId: '9NKVX66J0ZSK',
  },
  {
    howLongToBeatId: '47169',
    metaCriticId: 'deep-rock-galactic',
    title: 'Deep Rock Galactic',
    gamePassId: '9NHFVWX1V7QJ',
  },
  {
    metaCriticId: 'deliver-us-the-moon',
    title: 'Deliver Us The Moon.',
    gamePassId: '9PF6BS5DGNLX',
  },
  {
    howLongToBeatId: '55598',
    metaCriticId: 'descenders',
    title: 'Descenders',
    gamePassId: 'C37XBX7DCBZ0',
  },
  {
    howLongToBeatId: '60291',
    metaCriticId: 'desperados-iii',
    title: 'Desperados III',
    gamePassId: '9P1ZX74WPL68',
  },
  {
    howLongToBeatId: '71701',
    title: 'Disgaea 4 Complete+',
    gamePassId: '9PFJDSL1CC7G',
  },
  {
    howLongToBeatId: '26731',
    metaCriticId: 'dishonored-2',
    title: 'Dishonored 2',
    gamePassId: '9MW4RJDRSF78',
  },
  {
    howLongToBeatId: '4994',
    metaCriticId: 'disneyland-adventures',
    title: 'Disneyland Adventures',
    gamePassId: '9N6Z8DQXSQWH',
  },
  {
    howLongToBeatId: '2675',
    metaCriticId: 'dont-starve-together',
    title: "Don't Starve",
    gamePassId: 'C0XBNVR137DZ',
  },
  {
    howLongToBeatId: '51323',
    metaCriticId: 'donut-county',
    title: 'Donut County',
    gamePassId: '9N6V2181GHLM',
  },
  {
    howLongToBeatId: '57506',
    metaCriticId: 'doom-eternal',
    title: 'DOOM Eternal  ',
    gamePassId: '9PK09BL31FK1',
  },
  {
    howLongToBeatId: '53061',
    metaCriticId: 'double-kick-heroes',
    title: 'Double Kick Heroes',
    gamePassId: '9NJPT63K27W8',
  },
  {
    howLongToBeatId: '31178',
    metaCriticId: 'downwell',
    title: 'Downwell',
    gamePassId: '9P641Z19NT2S',
  },
  {
    howLongToBeatId: '69743',
    metaCriticId:
      'dragon-quest-xi-s-echoes-of-an-elusive-age---definitive-edition',
    title: 'DRAGON QUEST XI S: Echoes of an Elusive Age - Definitive Edition',
    gamePassId: '9PBDC0XZ8TXK',
  },
  {
    howLongToBeatId: '82637',
    metaCriticId: 'drake-hollow',
    title: 'Drake Hollow',
    gamePassId: '9PGNGGWBX1NR',
  },
  {
    howLongToBeatId: '17454',
    metaCriticId: 'dungeon-of-the-endless',
    title: 'Dungeon of the Endless',
    gamePassId: '9N46K0X6TBZK',
  },
  {
    howLongToBeatId: '65001',
    metaCriticId: 'eastshade',
    title: 'Eastshade',
    gamePassId: '9PLCR0FR564K',
  },
  {
    howLongToBeatId: '18226',
    metaCriticId: 'endless-legend',
    title: 'Endless Legend',
    gamePassId: '9NP09BFQNHCJ',
  },
  {
    howLongToBeatId: '41360',
    metaCriticId: 'endless-space-2',
    title: 'Endless Space 2',
    gamePassId: '9NV3Q7WVN2RB',
  },
  {
    howLongToBeatId: '35549',
    metaCriticId: 'enter-the-gungeon',
    title: 'Enter The Gungeon',
    gamePassId: '9NB65S6LFZRT',
  },
  {
    howLongToBeatId: '13304',
    metaCriticId: 'europa-universalis-iv',
    title: 'Europa Universalis IV',
    gamePassId: '9PHQJWGLTZM8',
  },
  {
    howLongToBeatId: '68644',
    metaCriticId: 'f1-2019',
    title: 'F1 2019 ',
    gamePassId: '9NL9VGSH00LL',
  },
  {
    howLongToBeatId: '57416',
    metaCriticId: 'fallout-76',
    title: 'Fallout 76 ',
    gamePassId: '9NKGNMNK3K3Z',
  },
  {
    howLongToBeatId: '3505',
    metaCriticId: 'final-fantasy-ix',
    title: 'FINAL FANTASY IX',
    gamePassId: '9NPGTNQFC8B5',
  },
  { title: 'FINAL FANTASY VII WINDOWS EDITION', gamePassId: '9PN0W216SKZB' },
  {
    title: 'FINAL FANTASY VIII Remastered WINDOWS EDITION',
    gamePassId: '9P35DPLN1JCN',
  },
  {
    howLongToBeatId: '20811',
    metaCriticId: 'five-nights-at-freddys',
    title: "Five Nights at Freddy's",
    gamePassId: '9N5253J559LR',
  },
  {
    howLongToBeatId: '22612',
    metaCriticId: 'five-nights-at-freddys-2',
    title: "Five Nights at Freddy's 2",
    gamePassId: '9NBR2ZSD99FX',
  },
  {
    howLongToBeatId: '24456',
    metaCriticId: 'five-nights-at-freddys',
    title: "Five Nights at Freddy's 3",
    gamePassId: '9P6N7LQ4HZFD',
  },
  {
    howLongToBeatId: '28975',
    metaCriticId: 'five-nights-at-freddys-4',
    title: "Five Nights at Freddy's 4",
    gamePassId: '9PLDLMPLR7JV',
  },
  {
    title: "Five Nights at Freddy's: Original Series",
    gamePassId: '9PJ2DSSXZR0P',
  },
  {
    howLongToBeatId: '45024',
    metaCriticId: 'crusader-kings-iii',
    title: 'For The King',
    gamePassId: '9NS1CD1V4BKW',
  },
  {
    howLongToBeatId: '62412',
    metaCriticId: 'forager',
    title: 'Forager',
    gamePassId: '9P5SFDNW6V13',
  },
  {
    howLongToBeatId: '55661',
    metaCriticId: 'forza-horizon-4',
    title: 'Forza Horizon 4 ',
    gamePassId: '9PNJXVCVWD4K',
  },
  {
    howLongToBeatId: '46400',
    metaCriticId: 'forza-motorsport-7',
    title: 'Forza Motorsport 7 ',
    gamePassId: '9N3NK5WW05HT',
  },
  {
    howLongToBeatId: '41585',
    metaCriticId: 'frostpunk',
    title: 'Frostpunk',
    gamePassId: '9NS0KH25D76X',
  },
  {
    howLongToBeatId: '44400',
    metaCriticId: 'full-throttle-remastered',
    title: 'Full Throttle Remastered',
    gamePassId: '9P3ZRGNQVC7D',
  },
  {
    howLongToBeatId: '67569',
    metaCriticId: 'gato-roboto',
    title: 'Gato Roboto',
    gamePassId: '9PBJQ90CT236',
  },
  {
    howLongToBeatId: '57422',
    metaCriticId: 'gears-5',
    title: 'Gears 5',
    gamePassId: 'C2KDNLT2H7DM',
  },
  {
    howLongToBeatId: '57422',
    metaCriticId: 'gears-5',
    title: 'Gears 5 ',
    gamePassId: '9P4KMR76PLLQ',
  },
  {
    howLongToBeatId: '26788',
    metaCriticId: 'gears-of-war-4',
    title: 'Gears of War 4',
    gamePassId: '9NBLGGH4PBBM',
  },
  {
    metaCriticId: 'gears-of-war-ultimate-edition-for-windows-10',
    title: 'Gears of War: Ultimate Edition for ',
    gamePassId: '9NBLGGH3SHM5',
  },
  {
    howLongToBeatId: '57740',
    metaCriticId: 'gears-tactics',
    title: 'Gears Tactics',
    gamePassId: '9NN3HCKW5TPC',
  },
  {
    howLongToBeatId: '21687',
    metaCriticId: 'ghost-of-a-tale',
    title: 'Ghost of a Tale',
    gamePassId: '9PJR5XZG5CNS',
  },
  {
    howLongToBeatId: '17536',
    metaCriticId: 'goat-simulator',
    title: 'Goat Simulator ',
    gamePassId: '9MXWKHJ3VZZH',
  },
  {
    howLongToBeatId: '34956',
    metaCriticId: 'golf-with-your-friends',
    title: 'Golf With Your Friends',
    gamePassId: '9MVK5W0HMRP7',
  },
  { howLongToBeatId: '84332', title: 'GONNER2 ', gamePassId: '9P44W70MC99Z' },
  {
    howLongToBeatId: '62519',
    metaCriticId: 'greedfall',
    title: 'GreedFall',
    gamePassId: '9PB79JST8PDH',
  },
  {
    howLongToBeatId: '23473',
    metaCriticId: 'grim-fandango-remastered',
    title: 'Grim Fandango Remastered',
    gamePassId: '9PC288TN7R8K',
  },
  {
    howLongToBeatId: '77857',
    metaCriticId: 'grounded-gus-jewell',
    title: 'Grounded',
    gamePassId: '9PJTHRNVH62H',
  },
  {
    howLongToBeatId: '59509',
    metaCriticId: 'guacamelee!-2',
    title: 'Guacamelee! 2',
    gamePassId: '9NVK1W7L093S',
  },
  {
    howLongToBeatId: '22622',
    metaCriticId: 'halo-2-anniversary',
    title: 'Halo 2: Anniversary',
    gamePassId: '9P5739G419LD',
  },
  {
    howLongToBeatId: '4263',
    metaCriticId: 'halo-the-master-chief-collection---halo-3',
    title: 'Halo 3',
    gamePassId: '9PGL2Z1H9M4R',
  },
  {
    howLongToBeatId: '4264',
    metaCriticId: 'halo-the-master-chief-collection---halo-3-odst',
    title: 'Halo 3: ODST',
    gamePassId: '9P6VZCRGXFMX',
  },
  {
    howLongToBeatId: '4265',
    metaCriticId: 'halo-the-master-chief-collection---halo-4',
    title: 'Halo 4',
    gamePassId: '9P8CFXZH93CK',
  },
  {
    howLongToBeatId: '37985',
    metaCriticId: 'halo-wars-2',
    title: 'Halo Wars 2',
    gamePassId: '9NBLGGH5WMKM',
  },
  {
    howLongToBeatId: '59330',
    metaCriticId: 'halo-wars-2',
    title: 'Halo Wars 2: ',
    gamePassId: '9NBLGGH515BD',
  },
  {
    howLongToBeatId: '4267',
    metaCriticId: 'halo-wars-definitive-edition',
    title: 'Halo Wars: Definitive Edition ',
    gamePassId: '9NBLGGH5WLR0',
  },
  {
    howLongToBeatId: '4270',
    metaCriticId: 'halo-combat-evolved-anniversary',
    title: 'Halo: Combat Evolved Anniversary',
    gamePassId: '9NWQMVSB63N4',
  },
  {
    howLongToBeatId: '4271',
    metaCriticId: 'halo-reach-remastered',
    title: 'Halo: Reach',
    gamePassId: '9N9WZT3PJ27W',
  },
  {
    howLongToBeatId: '4272',
    metaCriticId: 'halo-spartan-assault',
    title: 'Halo: Spartan Assault',
    gamePassId: '9WZDNCRFHWFH',
  },
  {
    howLongToBeatId: '22540',
    metaCriticId: 'halo-spartan-strike',
    title: 'Halo: Spartan Strike',
    gamePassId: '9WZDNCRFJBFJ',
  },
  {
    howLongToBeatId: '22621',
    metaCriticId: 'halo-the-master-chief-collection---halo-3',
    title: 'Halo: The Master Chief Collection',
    gamePassId: '9NTM9HXNLSZX',
  },
  {
    howLongToBeatId: '80569',
    metaCriticId: 'sky-haven',
    title: 'Haven',
    gamePassId: '9NZL91Q08XRV',
  },
  {
    howLongToBeatId: '37795',
    metaCriticId: 'hearts-of-iron-iv',
    title: 'Hearts of Iron IV',
    gamePassId: '9NF6WPNS1S73',
  },
  {
    howLongToBeatId: '70193',
    metaCriticId: 'farm-frenzy-heave-ho',
    title: 'Heave Ho',
    gamePassId: '9P8JHRDVBLHB',
  },
  {
    howLongToBeatId: '41638',
    metaCriticId: 'hellblade-senuas-sacrifice',
    title: "Hellblade: Senua's Sacrifice",
    gamePassId: '9NCLP4LV5K7Z',
  },
  {
    howLongToBeatId: '40794',
    metaCriticId: 'hello-neighbor',
    title: 'Hello Neighbor',
    gamePassId: '9NDDH3R9DF40',
  },
  {
    howLongToBeatId: '26286',
    metaCriticId: 'hollow-knight',
    title: 'Hollow Knight',
    gamePassId: '9PKM22F7C9K5',
  },
  {
    howLongToBeatId: '4530',
    metaCriticId: 'hotline-miami',
    title: 'Hotline Miami',
    gamePassId: '9PPCS86WS28Z',
  },
  {
    howLongToBeatId: '38887',
    metaCriticId: 'human-fall-flat',
    title: 'Human Fall Flat',
    gamePassId: '9MT4HS1CP72W',
  },
  {
    howLongToBeatId: '77188',
    metaCriticId: 'hyperdot',
    title: 'HyperDot',
    gamePassId: '9NVVJ8TBD7KP',
  },
  {
    howLongToBeatId: '65593',
    metaCriticId: 'hypnospace-outlaw',
    title: 'Hypnospace Outlaw',
    gamePassId: '9PM3NVB3PXG0',
  },
  {
    howLongToBeatId: '80165',
    metaCriticId: 'ikenfell',
    title: 'Ikenfell',
    gamePassId: '9N2X1J99S4M9',
  },
  {
    howLongToBeatId: '37862',
    metaCriticId: 'injustice-2',
    title: 'Injustice 2',
    gamePassId: '9PHT4W7WBBDQ',
  },
  {
    howLongToBeatId: '56403',
    metaCriticId: 'it-lurks-below',
    title: 'It Lurks Below',
    gamePassId: '9PFW68JLS81F',
  },
  {
    howLongToBeatId: '33020',
    metaCriticId: 'katana-zero',
    title: 'Katana Zero',
    gamePassId: '9P6CVNVMK56R',
  },
  {
    howLongToBeatId: '36847',
    metaCriticId: 'kathy-rain',
    title: 'Kathy Rain',
    gamePassId: '9P8HN2T2SZGB',
  },
  {
    metaCriticId: 'killer-instinct-definitive-edition',
    title: 'Killer Instinct: Definitive Edition',
    gamePassId: '9NBLGGH51BMC',
  },
  {
    howLongToBeatId: '67984',
    metaCriticId: 'knights-and-bikes',
    title: 'Knights and Bikes',
    gamePassId: '9P64KV1HQK07',
  },
  {
    howLongToBeatId: '76093',
    metaCriticId: 'levelhead',
    title: 'Levelhead',
    gamePassId: '9PJZBB8FWK8H',
  },
  {
    howLongToBeatId: '71406',
    metaCriticId: 'lonely-mountains-downhill',
    title: 'Lonely Mountains: Downhill',
    gamePassId: '9MV6MCVLT8GR',
  },
  {
    howLongToBeatId: '5478',
    metaCriticId: 'machinarium',
    title: 'Machinarium',
    gamePassId: '9N83GKZLC8BK',
  },
  { title: 'MARVEL VS. CAOM: INFINITE', gamePassId: '9PGSCB1X2P7G' },
  {
    howLongToBeatId: '67949',
    metaCriticId: 'mechwarrior-5-mercenaries',
    title: 'MechWarrior 5: Mercenaries',
    gamePassId: '9PB86W3JK8Z5',
  },
  { title: 'Microsoft Flight Simulator: Standard', gamePassId: '9NXN8GF8N9HT' },
  {
    howLongToBeatId: '44022',
    metaCriticId: 'middle-earth-shadow-of-war',
    title: 'Middle-earth: Shadow of War',
    gamePassId: '9PDV8FKWP3B4',
  },
  {
    howLongToBeatId: '68149',
    metaCriticId: 'minecraft-dungeons-howling-peaks',
    title: 'Minecraft Dungeons',
    gamePassId: '9P8MK4NC0LJB',
  },
  {
    howLongToBeatId: '71153',
    metaCriticId: 'mistover-dr-fausts-otherworldly-adventure',
    title: 'MISTOVER',
    gamePassId: '9P8K66J3CQ9S',
  },
  {
    howLongToBeatId: '35555',
    metaCriticId: 'momodora-reverie-under-the-moonlight',
    title: 'Momodora: Reverie Under the Moonlight',
    gamePassId: '9NZL00LF4V58',
  },
  {
    howLongToBeatId: '70012',
    metaCriticId: 'monster-sanctuary',
    title: 'Monster Sanctuary',
    gamePassId: '9PBWWQGXVMKC',
  },
  {
    howLongToBeatId: '78633',
    metaCriticId: 'monster-train',
    title: 'Monster Train',
    gamePassId: '9NP4BGBLLLXM',
  },
  {
    howLongToBeatId: '56787',
    metaCriticId: 'moonlighter',
    title: 'Moonlighter',
    gamePassId: '9P8XJRLCLH2P',
  },
  {
    howLongToBeatId: '85965',
    metaCriticId: 'morkredd',
    title: 'Morkredd',
    gamePassId: '9PKD7RG0TQP4',
  },
  {
    howLongToBeatId: '22543',
    metaCriticId: 'mother-russia-bleeds',
    title: 'Mother Russia Bleeds',
    gamePassId: '9NVFHBKDLPM4',
  },
  { title: 'MotoGP20 -  Edition', gamePassId: '9N88HSBP6RJ8' },
  {
    howLongToBeatId: '6240',
    metaCriticId: 'mount-blade-warband',
    title: 'Mount & Blade: Warband ',
    gamePassId: '9PFZC53PVTDB',
  },
  {
    howLongToBeatId: '75031',
    metaCriticId: 'moving-out',
    title: 'Moving Out',
    gamePassId: '9N9H593X8SVP',
  },
  {
    howLongToBeatId: '52787',
    metaCriticId: 'my-time-at-portia',
    title: 'My Time At Portia',
    gamePassId: '9NBLSN1JP7TH',
  },
  {
    howLongToBeatId: '77366',
    metaCriticId: 'neon-abyss',
    title: 'Neon Abyss',
    gamePassId: '9PLWSGHFQ4PS',
  },
  {
    howLongToBeatId: '68733',
    metaCriticId: 'neoverse',
    title: 'Neoverse',
    gamePassId: '9NNSTP6KJTZ9',
  },
  {
    howLongToBeatId: '71552',
    metaCriticId: 'new-super-luckys-tale',
    title: "New Super Lucky's Tale",
    gamePassId: '9MZN3SMXN824',
  },
  {
    howLongToBeatId: '69216',
    metaCriticId: 'night-call',
    title: 'Night Call',
    gamePassId: '9N5KSQG0R9TB',
  },
  { title: 'Night in the Woods Win10', gamePassId: '9MV13BTTCKLL' },
  {
    howLongToBeatId: '20074',
    metaCriticId: 'no-mans-sky',
    title: "No Man's Sky",
    gamePassId: 'BQVQTL3PCH05',
  },
  {
    howLongToBeatId: '69248',
    metaCriticId: 'nowhere-prophet',
    title: 'Nowhere Prophet',
    gamePassId: '9P01NRSZCVR6',
  },
  {
    howLongToBeatId: '67287',
    metaCriticId: 'grav-lab-gravitational-testing-facility-and-observations',
    title: 'Observation',
    gamePassId: '9PBLH1322GX0',
  },
  {
    howLongToBeatId: '36755',
    metaCriticId: 'ori-and-the-blind-forest-definitive-edition',
    title: 'Ori and the Blind Forest: Definitive Edition',
    gamePassId: '9NBLGGH1Z6FB',
  },
  {
    howLongToBeatId: '46428',
    metaCriticId: 'ori-and-the-will-of-the-wisps',
    title: 'Ori and the Will of the Wisps',
    gamePassId: '9N8CD0XZKLP4',
  },
  {
    howLongToBeatId: '80631',
    metaCriticId: 'out-of-the-park-baseball-21',
    title: 'Out of the Park Baseball 21',
    gamePassId: '9NNW9V8DVPG6',
  },
  {
    howLongToBeatId: '57518',
    metaCriticId: 'overcooked!-2',
    title: 'Overcooked! 2',
    gamePassId: '9PGB72NFG5JN',
  },
  {
    howLongToBeatId: '33620',
    metaCriticId: 'oxenfree',
    title: 'Oxenfree',
    gamePassId: '9NBLGGH6CTZ5',
  },
  {
    howLongToBeatId: '47069',
    metaCriticId: 'pandemic-the-board-game',
    title: 'Pandemic: The Board Game',
    gamePassId: '9P8Q4W21QQZ2',
  },
  {
    howLongToBeatId: '53702',
    metaCriticId: 'phoenix-point',
    title: 'Phoenix Point',
    gamePassId: '9P1P5Q3BNM7J',
  },
  { title: 'Pikuniku Win10', gamePassId: '9N8QNKN5ZKTH' },
  { title: 'Pillars of Eternity: Hero Edition', gamePassId: '9P5LZC1KB48V' },
  {
    howLongToBeatId: '78632',
    metaCriticId: 'plebby-quest-the-crusades',
    title: 'Plebby Quest: The Crusades',
    gamePassId: '9MWBPSQ5PKQR',
  },
  {
    howLongToBeatId: '65929',
    metaCriticId: 'power-rangers-battle-for-the-grid---scorpina',
    title: 'Power Rangers: Battle for the Grid',
    gamePassId: '9P5VMG8D4P4B',
  },
  {
    howLongToBeatId: '7308',
    metaCriticId: 'prison-architect',
    title: 'Prison Architect ',
    gamePassId: '9P5S2J2VLLPR',
  },
  {
    howLongToBeatId: '68128',
    metaCriticId: 'project-winter',
    title: 'Project Winter',
    gamePassId: '9P3SX4G50LZ1',
  },
  {
    howLongToBeatId: '58031',
    metaCriticId: 'god-eater-2-rage-burst',
    title: 'RAGE 2 ',
    gamePassId: '9P2J7WHV0K4N',
  },
  {
    howLongToBeatId: '26789',
    metaCriticId: 'recore',
    title: 'ReCore',
    gamePassId: '9NBLGGH1Z6FQ',
  },
  {
    howLongToBeatId: '38051',
    metaCriticId: 'resident-evil-7-biohazard',
    title: 'RESIDENT EVIL 7 biohazard',
    gamePassId: '9NBLGGH4SPK6',
  },
  {
    howLongToBeatId: '19796',
    metaCriticId: 'rise-of-nations-extended-edition',
    title: 'Rise of Nations: Extended Edition',
    gamePassId: '9NS84HCWZD8B',
  },
  {
    howLongToBeatId: '69993',
    metaCriticId: 'river-city-girls',
    title: 'River City Girls',
    gamePassId: '9PGNT102001S',
  },
  { title: 'Rush: A DisneyPixar Adventure', gamePassId: '9P3PL76N0KWZ' },
  {
    howLongToBeatId: '68579',
    metaCriticId: 'scourgebringer',
    title: 'ScourgeBringer',
    gamePassId: '9NXPV1T3WS34',
  },
  {
    howLongToBeatId: '38053',
    metaCriticId: 'sea-of-thieves',
    title: 'Sea of Thieves',
    gamePassId: '9P2N57MC619K',
  },
  {
    howLongToBeatId: '39740',
    metaCriticId: 'shadow-warrior-2',
    title: 'Shadow Warrior 2',
    gamePassId: '9P6SFBR1TCWQ',
  },
  {
    howLongToBeatId: '51390',
    metaCriticId: 'slay-the-spire',
    title: 'Slay The Spire',
    gamePassId: '9MZQR8317S3B',
  },
  {
    howLongToBeatId: '68189',
    metaCriticId: 'spiritfarer',
    title: 'Spiritfarer',
    gamePassId: '9NG5L58FD3X5',
  },
  {
    howLongToBeatId: '71955',
    metaCriticId: 'star-renegades',
    title: 'Star Renegades',
    gamePassId: '9PK5S1QKV10D',
  },
  {
    howLongToBeatId: '9149',
    metaCriticId: 'starbound',
    title: 'Starbound',
    gamePassId: '9MTSBWPWPQVQ',
  },
  {
    metaCriticId: 'state-of-decay-2-juggernaut-edition',
    title: 'State of Decay 2: Juggernaut Edition',
    gamePassId: '9NT4X7P8B9NB',
  },
  {
    howLongToBeatId: '37186',
    metaCriticId: 'stellaris',
    title: 'Stellaris',
    gamePassId: '9NXQPGMR917R',
  },
  {
    howLongToBeatId: '68766',
    metaCriticId: 'stranger-things-3-the-game',
    title: 'Stranger Things 3: The Game',
    gamePassId: '9PMDDQ228FQD',
  },
  {
    howLongToBeatId: '76482',
    metaCriticId: 'streets-of-rage-4',
    title: 'Streets of Rage 4',
    gamePassId: '9N7H54KNCB9N',
  },
  {
    howLongToBeatId: '44813',
    metaCriticId: 'streets-of-rogue',
    title: 'Streets of Rogue',
    gamePassId: '9NKRBSZXQ2HM',
  },
  {
    howLongToBeatId: '23740',
    metaCriticId: 'subnautica',
    title: 'Subnautica',
    gamePassId: 'BX3S1Q5DVHRD',
  },
  {
    howLongToBeatId: '21278',
    metaCriticId: 'sunset-overdrive',
    title: 'Sunset Overdrive',
    gamePassId: '9NNLBL0T2Z43',
  },
  {
    howLongToBeatId: '46426',
    metaCriticId: 'super-luckys-tale',
    title: "Super Lucky's Tale",
    gamePassId: '9PLMGFWCFZ9G',
  },
  {
    howLongToBeatId: '45951',
    metaCriticId: 'surviving-mars',
    title: 'Surviving Mars',
    gamePassId: '9MXB71Q4VWGJ',
  },
  {
    howLongToBeatId: '64159',
    metaCriticId: 'tales-of-vesperia-definitive-edition',
    title: 'Tales of Vesperia: Definitive Edition',
    gamePassId: '9N5QWL08HRTR',
  },
  { title: 'Tell Me Why: Chapters 1-3', gamePassId: '9NF83PRZK6K3' },
  {
    howLongToBeatId: '84923',
    metaCriticId: 'tetris-effect-connected',
    title: 'Tetris Effect: Connected',
    gamePassId: '9PPBVK3TK83M',
  },
  {
    howLongToBeatId: '9772',
    title: "The Bard's Tale ARPG : Remastered and Resnarkled",
    gamePassId: '9PN3VDFTB5HZ',
  },
  {
    howLongToBeatId: '69339',
    metaCriticId: 'the-bards-tale-iv-directors-cut',
    title: "The Bard's Tale IV: Director's Cut",
    gamePassId: 'C2B4T86TXLRS',
  },
  {
    howLongToBeatId: '59950',
    metaCriticId: 'the-bards-tale-trilogy-remaster',
    title: "The Bard's Tale Trilogy",
    gamePassId: '9MVN4ND41DD3',
  },
  {
    howLongToBeatId: '69525',
    metaCriticId: 'the-dark-crystal-age-of-resistance-tactics',
    title: 'The Dark Crystal: Age of Resistance Tactics',
    gamePassId: '9NPWSCWJGHL1',
  },
  {
    howLongToBeatId: '67361',
    metaCriticId: 'the-dark-pictures-anthology-man-of-medan',
    title: 'The Dark Pictures Anthology: Man Of Medan',
    gamePassId: '9N3TF0CG8NZB',
  },
  {
    howLongToBeatId: '83463',
    metaCriticId: 'the-falconeer',
    title: 'The Falconeer',
    gamePassId: '9N8J0T5HCDB9',
  },
  {
    howLongToBeatId: '56088',
    metaCriticId: 'the-gardens-between',
    title: 'The Gardens Between',
    gamePassId: '9P4Z4TW66LPV',
  },
  {
    howLongToBeatId: '21471',
    metaCriticId: 'the-long-dark',
    title: 'The Long Dark',
    gamePassId: '9NFKN56ZBMR0',
  },
  {
    howLongToBeatId: '78037',
    metaCriticId: 'the-medium',
    title: 'The Medium',
    gamePassId: '9NFSR96G6K4N',
  },
  {
    howLongToBeatId: '60176',
    metaCriticId: 'the-messenger',
    title: 'The Messenger',
    gamePassId: '9NNFBW3NGV9K',
  },
  {
    howLongToBeatId: '62935',
    metaCriticId: 'the-outer-worlds-peril-on-gorgon',
    title: 'The Outer Worlds',
    gamePassId: '9MWD2Z8L1FBQ',
  },
  {
    howLongToBeatId: '67880',
    metaCriticId: 'the-surge-2',
    title: 'The Surge 2',
    gamePassId: '9NLDM4DGX41G',
  },
  {
    metaCriticId: 'the-swords-of-ditto-mormos-curse',
    title: "The Swords of Ditto: Mormo's Curse",
    gamePassId: '9NF2DDV5RTH8',
  },
  {
    howLongToBeatId: '70671',
    metaCriticId: 'the-touryst',
    title: 'The Touryst',
    gamePassId: '9N9W1JK1X5QJ',
  },
  {
    metaCriticId: 'the-yakuza-remastered-collection',
    title: 'The Yakuza Remastered Collection for ',
    gamePassId: '9NBTL551XL5N',
  },
  {
    howLongToBeatId: '40500',
    metaCriticId: 'thumper',
    title: 'Thumper',
    gamePassId: '9PHV10KXLJZT',
  },
  {
    howLongToBeatId: '10533',
    metaCriticId: 'torment-tides-of-numenera',
    title: 'Torment: Tides of Numenera',
    gamePassId: '9NC0071DJ6XC',
  },
  {
    howLongToBeatId: '52878',
    metaCriticId: 'totally-accurate-battle-simulator',
    title: 'Totally Accurate Battle Simulator ',
    gamePassId: '9PC4RWP34M2D',
  },
  {
    howLongToBeatId: '60261',
    metaCriticId: 'touhou-luna-nights',
    title: 'Touhou Luna Nights',
    gamePassId: '9NBLGJQQBHH4',
  },
  {
    howLongToBeatId: '56055',
    metaCriticId: 'trailmakers',
    title: 'Trailmakers',
    gamePassId: '9NSFGM8J6MBJ',
  },
  {
    howLongToBeatId: '74885',
    metaCriticId: 'train-sim-world-2020',
    title: 'Train Sim World 2020',
    gamePassId: '9PMT49X8ZGM2',
  },
  {
    howLongToBeatId: '60043',
    metaCriticId: 'two-point-hospital',
    title: 'Two Point Hospital',
    gamePassId: '9N08S5VPC4SX',
  },
  {
    howLongToBeatId: '69349',
    metaCriticId: 'the-incredibles-rise-of-the-underminer',
    title: 'UnderMine',
    gamePassId: '9N52CQMFH3BB',
  },
  {
    howLongToBeatId: '64458',
    metaCriticId: 'unruly-heroes',
    title: 'Unruly Heroes ',
    gamePassId: '9P3SS6K8ZQ57',
  },
  {
    howLongToBeatId: '49816',
    metaCriticId: 'unto-the-end',
    title: 'Unto The End',
    gamePassId: '9MVJ0W5N2L2Q',
  },
  {
    howLongToBeatId: '25099',
    metaCriticId: 'va-11-hall-a-cyberpunk-bartender-action',
    title: 'VA-11 Hall-A: Cyberpunk Bartender Action',
    gamePassId: '9P9C1HB78K05',
  },
  {
    howLongToBeatId: '67877',
    metaCriticId: 'vambrace-cold-soul',
    title: 'Vambrace: Cold Soul',
    gamePassId: '9N171CGFVT1L',
  },
  {
    howLongToBeatId: '67475',
    metaCriticId: 'void-bastards-bang-tydy',
    title: 'Void Bastards',
    gamePassId: '9PJ1CGLKQSWS',
  },
  {
    howLongToBeatId: '61653',
    metaCriticId: 'wargroove',
    title: 'Wargroove',
    gamePassId: '9NRPTTJ94PCK',
  },
  {
    howLongToBeatId: '11099',
    metaCriticId: 'wasteland-2-directors-cut',
    title: "Wasteland 2: Director's Cut",
    gamePassId: 'C521HDXRTS7F',
  },
  {
    howLongToBeatId: '42532',
    metaCriticId: 'wasteland-3',
    title: 'Wasteland 3 ',
    gamePassId: '9NLT5XR52ZS7',
  },
  {
    howLongToBeatId: '74755',
    metaCriticId: 'wasteland-remastered',
    title: 'Wasteland Remastered',
    gamePassId: '9NGH1FK0RJGL',
  },
  {
    howLongToBeatId: '27102',
    metaCriticId: 'we-happy-few',
    title: 'We Happy Few',
    gamePassId: '9NBLGGH5342P',
  },
  {
    howLongToBeatId: '77696',
    metaCriticId: 'west-of-dead',
    title: 'West of Dead',
    gamePassId: '9NV0540N4JRN',
  },
  {
    howLongToBeatId: '45392',
    metaCriticId: 'what-remains-of-edith-finch',
    title: 'What Remains of Edith Finch',
    gamePassId: 'BSLGLG8P9T01',
  },
  { title: "Wilmot's Warehouse Win10", gamePassId: '9NCHVR5KH0RN' },
  {
    howLongToBeatId: '26294',
    metaCriticId: 'wizard-of-legend',
    title: 'Wizard of Legend',
    gamePassId: '9MZH0GG41HL9',
  },
  {
    howLongToBeatId: '57504',
    metaCriticId: 'wolfenstein-youngblood',
    title: 'Wolfenstein: Youngblood ',
    gamePassId: '9PHFTS44F99K',
  },
  {
    howLongToBeatId: '67201',
    metaCriticId: 'world-of-horror',
    title: 'WORLD OF HORROR ',
    gamePassId: '9N1FDTTSS49Z',
  },
  {
    howLongToBeatId: '64828',
    metaCriticId: 'world-war-z',
    title: 'World War Z',
    gamePassId: '9N015DFDMVK6',
  },
  {
    howLongToBeatId: '39481',
    metaCriticId: 'worms-wmd',
    title: 'Worms W.M.D',
    gamePassId: '9NVRZZJ4NG99',
  },
  {
    howLongToBeatId: '71596',
    metaCriticId: 'xeno-crisis',
    title: 'Xeno Crisis',
    gamePassId: '9PNBGZTL0Z1S',
  },
  { title: 'Yakuza 0 for ', gamePassId: '9PD0BJRBLRJM' },
  {
    metaCriticId: 'yakuza-3-remastered',
    title: 'Yakuza 3 Remastered for ',
    gamePassId: '9NC4QMRHCNZK',
  },
  {
    metaCriticId: 'yakuza-4-remastered',
    title: 'Yakuza 4 Remastered for ',
    gamePassId: '9NWZTB9JQG9S',
  },
  {
    metaCriticId: 'yakuza-5-remastered',
    title: 'Yakuza 5 Remastered for ',
    gamePassId: '9MVX1V7W5SW8',
  },
  {
    metaCriticId: 'yakuza-kiwami-2',
    title: 'Yakuza Kiwami 2 for ',
    gamePassId: '9MZNFNN3XJ3F',
  },
  {
    metaCriticId: 'yakuza-kiwami',
    title: 'Yakuza Kiwami for ',
    gamePassId: '9P40SC5DQ9K0',
  },
  {
    howLongToBeatId: '71500',
    metaCriticId: 'yes-your-grace',
    title: 'Yes, Your Grace',
    gamePassId: '9NX14Q0QZD1T',
  },
  {
    howLongToBeatId: '63089',
    metaCriticId: 'yiik-a-postmodern-rpg',
    title: 'YIIK: A Postmodern RPG',
    gamePassId: '9P3XR9QN0P4C',
  },
  {
    howLongToBeatId: '68031',
    metaCriticId: 'yooka-laylee-and-the-impossible-lair',
    title: 'Yooka-Laylee and the Impossible Lair',
    gamePassId: '9NB1LCQDPPM1',
  },
  {
    howLongToBeatId: '52069',
    metaCriticId: 'zoo-tycoon-ultimate-animal-collection',
    title: 'Zoo Tycoon: Ultimate Animal Collection',
    gamePassId: '9PJ06TZX4NMH',
  },
]
